#!/usr/bin/env node
// -----------------------------------------------------------------------------
// Generates app/scss/fontface/_index.scss with the web fonts embedded as
// base64 data URIs.
//
// RetroShare is a privacy tool and the node may be reached over Tor or a LAN
// address, so fonts are never fetched from a CDN. Embedding them goes one
// further: there is no separate request to fail, and no dependency on the
// service handing back font/woff2 for a .woff2 path. The whole UI is one HTML,
// one CSS and one JS file.
//
// Run via `npm run fonts`; `npm run build` runs it first.
// -----------------------------------------------------------------------------
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const DIR = path.join(__dirname, '..', 'assets', 'webfonts');
const OUT = path.join(__dirname, '..', 'app', 'scss', 'fontface', '_index.scss');

// Archivo latin is a single variable file covering the whole 400-700 range the
// type scale uses, which is why eight Roboto partials collapsed into three
// faces here.
const FACES = [
  { file: 'Archivo-Variable.woff2', family: 'Archivo', weight: '400 700' },
  { file: 'DMMono-Regular.woff2', family: 'DM Mono', weight: '400' },
  { file: 'DMMono-Medium.woff2', family: 'DM Mono', weight: '500' },
];

const missing = FACES.filter((f) => !fs.existsSync(path.join(DIR, f.file)));
if (missing.length) {
  console.error('Missing font files in assets/webfonts:');
  missing.forEach((f) => console.error('  ' + f.file));
  process.exit(1);
}

const blocks = FACES.map(({ file, family, weight }) => {
  const b64 = fs.readFileSync(path.join(DIR, file)).toString('base64');
  return `@font-face {
  font-family: '${family}';
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  font-weight: ${weight};
  font-style: normal;
  font-display: block;
}`;
});

fs.writeFileSync(OUT, `// -----------------------------------------------------------------------------
// GENERATED by make-src/fonts.js — do not edit.
//
// The fonts are embedded as data URIs so the UI makes no network request for
// them, on any transport, and cannot render in a fallback face because a path
// or MIME type was wrong. Edit the FACES list in make-src/fonts.js instead.
// -----------------------------------------------------------------------------

${blocks.join('\n\n')}
`);

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`fontface/_index.scss: ${FACES.length} faces embedded, ${kb} KB`);
